services:
  pg:
    image: postgres
    environment:
      POSTGRES_USER: "${GWWS_POSTGRES_USER}" 
      POSTGRES_DB: "${GWWS_POSTGRES_DB}"
      POSTGRES_PASSWORD: "${GWWS_POSTGRES_PASSWORD}"
    ports:
      - "5434:5434"
    volumes:
      - postgres-data:/var/lib/postgresql
    restart: unless-stopped
    command: -p 5434

  backend:
    build:
      context: .
    env_file: ".env"
    environment:
      GWWS_DATABASE_URL: "postgresql://${GWWS_POSTGRES_USER}:${GWWS_POSTGRES_PASSWORD}@glowwsdb:5444/${GWWS_POSTGRES_DB}"
    depends_on:
      - pg

volumes:
  postgres-data:

