services:
  pg:
    image: postgres
    env_file: ".env"
    ports:
      - "5434:5434"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    command: -p 5434

  backend:
    build:
      context: .
    env_file: ".env"
    environment:
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@pg:5434/${POSTGRES_DB}"
    depends_on:
      - pg

volumes:
  postgres-data:

